name: Nodejs Chart CI Pipeline

trigger:
  branches:
    include:
      - refs/tags/*

pr:
  branches:
    include:
      - master

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      name: hmcts/cnp-azuredevops-libraries
      endpoint: hmcts
      ref: marty/chart-release-bugfix

variables:
  - name: agentPool
    value: ubuntu-latest
  - name: acrName
    value: hmctspublic
  - name: acrResourceGroup
    value: rpe-acr-prod-rg
  - name: serviceConnection
    value: azurerm-prod
  - name: buildPath
    value: chart-nodejs/test-image
  - name: repoName
    value: chart-nodejs
  - name: valuesFile
    value: $(repoName)/ci-values.yaml
  - name: testAppImage
    value: hmctspublic.azurecr.io/hmcts/chart-nodejs

jobs:
  - job: Validate
    pool:
      vmImage: ${{ variables.agentPool }}
    steps:
      - checkout: self
        clean: true

      - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
          - template: steps/acr-build.yaml@cnp-azuredevops-libraries
            parameters:
              serviceConnection: $(serviceConnection)
              buildPath: $(buildPath)

      - template: steps/charts/validate.yaml@cnp-azuredevops-libraries
        parameters:
          chartNamespace: chart-tests
          chartName: nodejs
          chartReleaseName: chart-nodejs-ci-test
          helmInstallTimeout: "500"
          # chartPath: $(repoName)/
          valuesFile: $(valuesFile)
          ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
            additionalHelmArgs: --set image=$(testAppImage):pr-$(System.PullRequest.PullRequestNumber)

  - job: Release
    # Make sure we are on the master branch with a tag
    # to trigger this job

    condition: >
      and(
          succeeded(),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        )
    dependsOn: Validate
    pool:
      vmImage: ${{ variables.agentPool }}
    steps:
      - template: steps/charts/release.yaml@cnp-azuredevops-libraries
        parameters:
          chartNamespace: chart-tests
          chartName: nodejs
          chartReleaseName: chart-nodejs
