apiVersion: v1
description: A Helm chart for HMCTS nodejs apps
name: nodejs
version: 1.3.0
keywords:
- node
- javascript
- nodejs
sources:
  - https://github.com/hmcts/chart-nodejs
icon: https://nodejs.org/static/images/logos/nodejs-new-pantone-black.png
