{{ if or (.Values.ingressHost ) (.Values.registerAdditionalDns.enabled) }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "hmcts.releaseName" . }}
  labels:
    {{- ( include "labels" . ) | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClass }}
spec:
  rules:
  {{- if .Values.ingressHost }}
  - host: {{ tpl .Values.ingressHost $ }}
    http:
      paths:
      {{- ( include "hmcts.additionalPathBasedRoutes" .) | indent 4 }}
      - path: /
        backend:
          serviceName: {{ template "hmcts.releaseName" . }}
          servicePort: 80
  {{- end }}
  {{- if .Values.registerAdditionalDns.enabled }}
  - host: {{ .Values.registerAdditionalDns.prefix }}-{{ tpl .Values.registerAdditionalDns.primaryIngressHost $ }}
    http:
      paths:
      {{- ( include "hmcts.additionalPathBasedRoutes" .) | indent 4 }}
      - path: /
        backend:
          serviceName: {{ template "hmcts.releaseName" . }}
          servicePort: 80
  {{- end }}
{{- end }}
